// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Persona {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub photo_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrimaryToken {
    #[prost(string, tag = "1")]
    pub sub: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub jti: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub rjti: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub exp: i64,
    #[prost(int64, tag = "5")]
    pub iat: i64,
    #[prost(int64, tag = "6")]
    pub nbf: i64,
    #[prost(bool, tag = "7")]
    pub is_admin: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExtendedToken {
    #[prost(string, tag = "1")]
    pub sub: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub jti: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub rjti: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub exp: i64,
    #[prost(int64, tag = "5")]
    pub iat: i64,
    #[prost(int64, tag = "6")]
    pub nbf: i64,
    #[prost(bool, tag = "7")]
    pub is_admin: bool,
    #[prost(message, optional, tag = "8")]
    pub persona: ::core::option::Option<Persona>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateAccessTokenRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateAccessTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub claims: ::core::option::Option<PrimaryToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateRefreshTokenRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateRefreshTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub claims: ::core::option::Option<PrimaryToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateReAuthTokenRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateReAuthTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub claims: ::core::option::Option<PrimaryToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateSessionTokenRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateSessionTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub claims: ::core::option::Option<ExtendedToken>,
}
/// Generated client implementations.
pub mod token_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct TokenServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TokenServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TokenServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TokenServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TokenServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn validate_admin_access_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateAccessTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateAccessTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateAdminAccessToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateAdminAccessToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_admin_refresh_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateRefreshTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateRefreshTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateAdminRefreshToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateAdminRefreshToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_admin_re_auth_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateReAuthTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateReAuthTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateAdminReAuthToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateAdminReAuthToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_admin_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateAdminSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateAdminSessionToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_user_access_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateAccessTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateAccessTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateUserAccessToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateUserAccessToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_user_refresh_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateRefreshTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateRefreshTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateUserRefreshToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateUserRefreshToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_user_re_auth_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateReAuthTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateReAuthTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateUserReAuthToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateUserReAuthToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_user_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/token.TokenService/ValidateUserSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("token.TokenService", "ValidateUserSessionToken"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
